spring:
  elasticsearch:
    enable: false
    rest:
      uris: http://localhost:9200

queue:
  executor:
    enable: false
    size: 6

xyz:
  base:
    encrypt:
      # 默认关闭，需要使用，自己开启
      enable: true
      # 默认无需配置，有默认的实现，若自己去实现，配置加密算法的全限定路径，但请标准实现EncryptInterface接口
      # 请务必提供两种构造函数 1. 空构造 2. Map<String,String>单参构造
      algorithm:
      # 以上基础配置完毕后，以下为自定义配置，以默认实现为例，若完全自定义的以自己的定义为主
      attribute:
        publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCOJeJMYgXgz1K2xfCdwJp/npAVWO1s1dKmRGaxKgnbILHl2PpYUtY7hkTfwwREGeGI457IwsGo/TgAolF3TyyPlqocFEm/csyHhkDLIdcbS0eD/Zu/c34Av1TcauLEgBdahmXCIJglLElZ3iStsuqyMnxzQxo1Lbq9f456sONALwIDAQAB
        privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAI4l4kxiBeDPUrbF8J3Amn+ekBVY7WzV0qZEZrEqCdsgseXY+lhS1juGRN/DBEQZ4YjjnsjCwaj9OACiUXdPLI+WqhwUSb9yzIeGQMsh1xtLR4P9m79zfgC/VNxq4sSAF1qGZcIgmCUsSVneJK2y6rIyfHNDGjUtur1/jnqw40AvAgMBAAECgYAyoevpqUDOwwqDcB41EtX1f1VzRSnNCpzt/I9Xq9G26/5yEMebjmYg7cK6sYxjdZSQXgPBHx48Q3YfQ7Ig/WKxdfzsYc1VOcNZolJxnrWad447sEfF1cMwtYg93KfAZp6cG76Qivgx5UT3QAI+p6oCmCtOFCdTsxky2axL5i1OgQJBAPlSSmVrgQlI0rAsn9OvvPwd3nREwv+xJyp3xiHWaBKEweqt6GOw2qLux0JAzvLa8tEStanKqSXwOvhL2TYm5k0CQQCR9KgcxtSHxoU5QhjeevakV5UPLglJxAF9x6S1ElvrY+SlQGa0j5gea/tOO0PiLoQ5yBIthHNZ8QviVbHyH/ZrAkEAjiHEebbkk9dpDLgT0UkBMrUQaTX9+GgUjNhFImspX01BgzjrH1HmAjafb3ykvbvl6xyAZbA7533hEEWlKYLZjQJAPMEqeVAKh7oLGpp436Mvp5kNYxQ2qY39UO4ZkYXi3UjnlCIKnn5nQ8KPCTGCQFQ8lhDCAFBx865y0/P37mF/oQJAN0qUh4nARZaTyjJl9R9DGhKrFfpqoDiZNpJFi8keSGyF2jzrbVihRjBL9UdvJmBJi5R527EVB5aFYafOq0aifQ==